#!/usr/bin/env bash
# first test what is avablbe in the server
#then run the copy command ()scp()
ssh ubuntu@52.3.248.19 -i ~/.ssh/id_rsa 'ls ~/'
if [ $# -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o "StrictHostKeyChecking=no" -i "$4" "$1" "$3"@"$2":~/
fi
ssh ubuntu@52.3.248.19 -i ~/.ssh/id_rsa 'ls ~/'
