#!/usr/bin/env bash
# A script to install nginx

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
sudo service nginx reload
