#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.

sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
