#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
sudo kill "$(pgrep 'nginx' | head -1)"
