#!/usr/bin/env bash
# Prints "Best School" 10x, "bad luck" the 4th, "good luck" the 8th

i=1
while [ "$i" -le 10 ]
do
    if [ "$i" -eq 4 ]; then
	echo "bad luck"
    elif [ "$i" -eq 8 ]; then
	echo "good luck"
    else
	echo "Best School"
    fi
    (( i++ ))
done
