#!/usr/bin/env bash
# Script gives info on file (exist? empty? file and not directory?)

file="school"

if [ -e "$file" ]; then
    echo "school file exists"

    if [ -s "$file" ]; then
	echo "school file is not empty"
    else
	echo "school file is empty"
    fi

    if [ -f "$file" ]; then
	echo "school is a regular file"
   
