#!/usr/bin/env bash
# Script gives info on file (exist? empty? file and not directory?)

file="school"

if [ -e "$file" ]; then
    echo "$file school file exists"

    if [ -s "$file" ]; then
	echo "$file school file is not empty"
    else
	echo "$file school file is empty"
    fi

    if [ -f "$file" ]; then
	echo "$file school is a regular file"
    fi

else
    echo "$file"
fi
